---
# ServerINfoPE #
# Configuration File #
# By ZephyriusX #

#Plugin Settings#
Prefix_For_Plugin:
Symbol_Of_Color:

#Server Information#

Server_Owner:
Server_Birthday:
Server_Version:
Server_Plugin_Developer:
Server_Configer:

#Server Available#

Server_Website:
Server_E-mail:
Server_Facebook:
Server_TeamSpeak3:
Server_Skype:
Server_Instagramm:
Server_Mobilenumber:
Server_Twitter:
Server_Youtube_Channel:

#By ZephyriusX#
